<?php

declare(strict_types=1);

namespace Jaddek\Ixopay\Http\Enum;

interface Secure3DEnum
{
    public const SECURE_3D_OFF       = 'OFF';
    public const SECURE_3D_OPTIONAL  = 'OPTIONAL';
    public const SECURE_3D_MANDATORY = 'MANDATORY';

    public const SECURE_3D = [
        self::SECURE_3D_OFF,
        self::SECURE_3D_OPTIONAL,
        self::SECURE_3D_MANDATORY
    ];

    public const CHANNEL_APP_BASED               = '01';
    public const CHANNEL_BROWSER                 = '02';
    public const CHANNEL_3DS_REQUESTOR_INITIATED = '03';

    public const CHANNELS = [
        self::CHANNEL_APP_BASED,
        self::CHANNEL_BROWSER,
        self::CHANNEL_3DS_REQUESTOR_INITIATED
    ];

    public const AUTHENTICATION_INDICATOR_PAYMENT_TRANSACTION     = '01';
    public const AUTHENTICATION_INDICATOR_RECURRING_TRANSACTION   = '02';
    public const AUTHENTICATION_INDICATOR_INSTALLMENT_TRANSACTION = '03';
    public const AUTHENTICATION_INDICATOR_ADD_CARD                = '04';
    public const AUTHENTICATION_INDICATOR_MAINTAIN_CARD           = '05';
    public const AUTHENTICATION_INDICATOR_CARDHOLDER_VERIFICATION = '06';

    public const AUTHENTICATION_INDICATORS = [
        self::AUTHENTICATION_INDICATOR_PAYMENT_TRANSACTION,
        self::AUTHENTICATION_INDICATOR_RECURRING_TRANSACTION,
        self::AUTHENTICATION_INDICATOR_INSTALLMENT_TRANSACTION,
        self::AUTHENTICATION_INDICATOR_ADD_CARD,
        self::AUTHENTICATION_INDICATOR_MAINTAIN_CARD,
        self::AUTHENTICATION_INDICATOR_CARDHOLDER_VERIFICATION
    ];

    public const AUTHENTICATION_METHOD_NO_3DS                    = '01';
    public const AUTHENTICATION_METHOD_3DS_REQUESTOR_CREDENTIALS = '02';
    public const AUTHENTICATION_METHOD_3DS_FEDERATED_ID          = '03';
    public const AUTHENTICATION_METHOD_3DS_ISSUER_CREDENTIALS    = '04';
    public const AUTHENTICATION_METHOD_3DS_THIRD_PARTY           = '05';
    public const AUTHENTICATION_METHOD_3DS_FIDO                  = '06';

    public const AUTHENTICATION_METHODS = [
        self::AUTHENTICATION_METHOD_NO_3DS,
        self::AUTHENTICATION_METHOD_3DS_REQUESTOR_CREDENTIALS,
        self::AUTHENTICATION_METHOD_3DS_FEDERATED_ID,
        self::AUTHENTICATION_METHOD_3DS_ISSUER_CREDENTIALS,
        self::AUTHENTICATION_METHOD_3DS_THIRD_PARTY,
        self::AUTHENTICATION_METHOD_3DS_FIDO
    ];

    public const CHALLENGE_INDICATOR_NO_REFERENCE                             = '01';
    public const CHALLENGE_INDICATOR_NO_CHALLENGE_REQUESTED                   = '02';
    public const CHALLENGE_INDICATOR_CHALLENGE_3DS_REQUESTOR_PREFERENCE       = '03';
    public const CHALLENGE_INDICATOR_CHALLENGE_MANDATE                        = '04';
    public const CHALLENGE_INDICATOR_NO_REFERENCE_RISK_PERFORMED              = '05';
    public const CHALLENGE_INDICATOR_NO_REFERENCE_DATA_SHARE                  = '06';
    public const CHALLENGE_INDICATOR_NO_REFERENCE_STRONG_CONSUMER_AUTH        = '07';
    public const CHALLENGE_INDICATOR_NO_REFERENCE_UTILISE_WHITELIST_EXEMPTION = '08';
    public const CHALLENGE_INDICATOR_CHALLENGE_WHITELIST_PROMPT               = '09';

    public const CHALLENGE_INDICATORS = [
        self::CHALLENGE_INDICATOR_NO_REFERENCE,
        self::CHALLENGE_INDICATOR_NO_CHALLENGE_REQUESTED,
        self::CHALLENGE_INDICATOR_CHALLENGE_3DS_REQUESTOR_PREFERENCE,
        self::CHALLENGE_INDICATOR_CHALLENGE_MANDATE,
        self::CHALLENGE_INDICATOR_NO_REFERENCE_RISK_PERFORMED,
        self::CHALLENGE_INDICATOR_NO_REFERENCE_DATA_SHARE,
        self::CHALLENGE_INDICATOR_NO_REFERENCE_STRONG_CONSUMER_AUTH,
        self::CHALLENGE_INDICATOR_NO_REFERENCE_UTILISE_WHITELIST_EXEMPTION,
        self::CHALLENGE_INDICATOR_CHALLENGE_WHITELIST_PROMPT
    ];

    public const PRIOR_AUTHENTICATION_METHOD_FRICTIONLESS_AUTH    = '01';
    public const PRIOR_AUTHENTICATION_METHOD_CARDHOLDER_CHALLENGE = '02';
    public const PRIOR_AUTHENTICATION_METHOD_AVS_VERIFIED         = '03';
    public const PRIOR_AUTHENTICATION_METHOD_OTHER                = '04';

    public const PRIOR_AUTHENTICATION_METHODS = [
        self::PRIOR_AUTHENTICATION_METHOD_FRICTIONLESS_AUTH,
        self::PRIOR_AUTHENTICATION_METHOD_CARDHOLDER_CHALLENGE,
        self::PRIOR_AUTHENTICATION_METHOD_AVS_VERIFIED,
        self::PRIOR_AUTHENTICATION_METHOD_OTHER
    ];

    public const CARDHOLDER_ACCOUNT_TYPE_NOT_APPLICABLE = '01';
    public const CARDHOLDER_ACCOUNT_TYPE_CREDIT         = '02';
    public const CARDHOLDER_ACCOUNT_TYPE_DEBIT          = '03';
    public const CARDHOLDER_ACCOUNT_TYPE_JCB_PREPAID    = '04';

    public const CARDHOLDER_ACCOUNT_TYPES = [
        self::CARDHOLDER_ACCOUNT_TYPE_NOT_APPLICABLE,
        self::CARDHOLDER_ACCOUNT_TYPE_CREDIT,
        self::CARDHOLDER_ACCOUNT_TYPE_DEBIT,
        self::CARDHOLDER_ACCOUNT_TYPE_JCB_PREPAID
    ];

    public const CARDHOLDER_ACCOUNT_AGE_INDICATOR_NO_ACCOUNT         = '01';
    public const CARDHOLDER_ACCOUNT_AGE_INDICATOR_DURING_TRANSACTION = '02';
    public const CARDHOLDER_ACCOUNT_AGE_INDICATOR_LESS_THAN_30_DAYS  = '03';
    public const CARDHOLDER_ACCOUNT_AGE_INDICATOR_30_60_DAYS         = '04';
    public const CARDHOLDER_ACCOUNT_AGE_INDICATOR_MORE_THAN_60_DAYS  = '05';

    public const CARDHOLDER_ACCOUNT_AGE_INDICATORS = [
        self::CARDHOLDER_ACCOUNT_AGE_INDICATOR_NO_ACCOUNT,
        self::CARDHOLDER_ACCOUNT_AGE_INDICATOR_DURING_TRANSACTION,
        self::CARDHOLDER_ACCOUNT_AGE_INDICATOR_LESS_THAN_30_DAYS,
        self::CARDHOLDER_ACCOUNT_AGE_INDICATOR_30_60_DAYS,
        self::CARDHOLDER_ACCOUNT_AGE_INDICATOR_MORE_THAN_60_DAYS,
    ];

    public const CARDHOLDER_ACCOUNT_CHANGE_INDICATOR_DURING_TRANSACTION = '01';
    public const CARDHOLDER_ACCOUNT_CHANGE_INDICATOR_LESS_THAN_30_DAYS  = '02';
    public const CARDHOLDER_ACCOUNT_CHANGE_INDICATOR_30_60_DAYS         = '03';
    public const CARDHOLDER_ACCOUNT_CHANGE_INDICATOR_MORE_THAN_60_DAYS  = '04';

    public const CARDHOLDER_ACCOUNT_CHANGE_INDICATORS = [
        self::CARDHOLDER_ACCOUNT_CHANGE_INDICATOR_DURING_TRANSACTION,
        self::CARDHOLDER_ACCOUNT_CHANGE_INDICATOR_LESS_THAN_30_DAYS,
        self::CARDHOLDER_ACCOUNT_CHANGE_INDICATOR_30_60_DAYS,
        self::CARDHOLDER_ACCOUNT_CHANGE_INDICATOR_MORE_THAN_60_DAYS,
    ];

    public const CARDHOLDER_ACCOUNT_PASSWORD_CHANGE_INDICATOR_NO_CHANGE                 = '01';
    public const CARDHOLDER_ACCOUNT_PASSWORD_CHANGE_INDICATOR_CHANGE_DURING_TRANSACTION = '02';
    public const CARDHOLDER_ACCOUNT_PASSWORD_CHANGE_INDICATOR_LESS_THAN_30_DAYS         = '03';
    public const CARDHOLDER_ACCOUNT_PASSWORD_CHANGE_INDICATOR_30_60_DAYS                = '04';
    public const CARDHOLDER_ACCOUNT_PASSWORD_CHANGE_INDICATOR_MORE_THAN_60_DAYS         = '05';

    public const CARDHOLDER_ACCOUNT_PASSWORD_CHANGE_INDICATORS = [
        self::CARDHOLDER_ACCOUNT_PASSWORD_CHANGE_INDICATOR_NO_CHANGE,
        self::CARDHOLDER_ACCOUNT_PASSWORD_CHANGE_INDICATOR_CHANGE_DURING_TRANSACTION,
        self::CARDHOLDER_ACCOUNT_PASSWORD_CHANGE_INDICATOR_LESS_THAN_30_DAYS,
        self::CARDHOLDER_ACCOUNT_PASSWORD_CHANGE_INDICATOR_30_60_DAYS,
        self::CARDHOLDER_ACCOUNT_PASSWORD_CHANGE_INDICATOR_MORE_THAN_60_DAYS,
    ];

    public const SHIPPING_ADDRESS_USAGE_INDICATOR_CHANGE_DURING_TRANSACTION = '01';
    public const SHIPPING_ADDRESS_USAGE_INDICATOR_LESS_THAN_30_DAYS         = '02';
    public const SHIPPING_ADDRESS_USAGE_INDICATOR_30_60_DAYS                = '03';
    public const SHIPPING_ADDRESS_USAGE_INDICATOR_MORE_THAN_60_DAYS         = '04';

    public const SHIPPING_ADDRESS_USAGE_INDICATORS = [
        self::SHIPPING_ADDRESS_USAGE_INDICATOR_CHANGE_DURING_TRANSACTION,
        self::SHIPPING_ADDRESS_USAGE_INDICATOR_LESS_THAN_30_DAYS,
        self::SHIPPING_ADDRESS_USAGE_INDICATOR_30_60_DAYS,
        self::SHIPPING_ADDRESS_USAGE_INDICATOR_MORE_THAN_60_DAYS,
    ];

    public const SUSPICIOUS_ACCOUNT_ACTIVITY_INDICATOR_NO_ACTIVITY         = '01';
    public const SUSPICIOUS_ACCOUNT_ACTIVITY_INDICATOR_SUSPICIOUS_ACTIVITY = '02';

    public const SUSPICIOUS_ACCOUNT_ACTIVITY_INDICATORS = [
        self::SUSPICIOUS_ACCOUNT_ACTIVITY_INDICATOR_NO_ACTIVITY,
        self::SUSPICIOUS_ACCOUNT_ACTIVITY_INDICATOR_SUSPICIOUS_ACTIVITY,
    ];

    public const SHIPPING_NAME_EQUAL_INDICATOR_IDENTICAL = '01';
    public const SHIPPING_NAME_EQUAL_INDICATOR_DIFFERENT = '02';

    public const SHIPPING_NAME_EQUAL_INDICATORS = [
        self::SHIPPING_NAME_EQUAL_INDICATOR_IDENTICAL,
        self::SHIPPING_NAME_EQUAL_INDICATOR_DIFFERENT,
    ];

    public const PAYMENT_ACCOUNT_AGE_INDICATOR_NO_ACCOUNT         = '01';
    public const PAYMENT_ACCOUNT_AGE_INDICATOR_DURING_TRANSACTION = '02';
    public const PAYMENT_ACCOUNT_AGE_INDICATOR_LESS_THAN_30_DAYS  = '03';
    public const PAYMENT_ACCOUNT_AGE_INDICATOR_30_60_DAYS         = '04';
    public const PAYMENT_ACCOUNT_AGE_INDICATOR_MORE_THAN_60_DAYS  = '05';

    public const PAYMENT_ACCOUNT_AGE_INDICATORS = [
        self::PAYMENT_ACCOUNT_AGE_INDICATOR_NO_ACCOUNT,
        self::PAYMENT_ACCOUNT_AGE_INDICATOR_DURING_TRANSACTION,
        self::PAYMENT_ACCOUNT_AGE_INDICATOR_LESS_THAN_30_DAYS,
        self::PAYMENT_ACCOUNT_AGE_INDICATOR_30_60_DAYS,
        self::PAYMENT_ACCOUNT_AGE_INDICATOR_MORE_THAN_60_DAYS,
    ];

    public const BILLING_SHIPPING_ADDRESS_MATCH_YES = 'Y';
    public const BILLING_SHIPPING_ADDRESS_MATCH_NO  = 'N';

    public const BILLING_SHIPPING_ADDRESS_MATCHES = [
        self::BILLING_SHIPPING_ADDRESS_MATCH_YES,
        self::BILLING_SHIPPING_ADDRESS_MATCH_NO,
    ];

    public const SHIP_INDICATOR_CARDHOLDER_BILLING_ADDRESS           = '01';
    public const SHIP_INDICATOR_ANOTHER_VERIFIED_ADDRESS             = '02';
    public const SHIP_INDICATOR_DIFFERENT_CARDHOLDER_BILLING_ADDRESS = '03';
    public const SHIP_INDICATOR_SHIP_TO_STORE                        = '04';
    public const SHIP_INDICATOR_DIGITAL_GOODS                        = '05';
    public const SHIP_INDICATOR_TRAVEL_EVENT                         = '06';
    public const SHIP_INDICATOR_OTHER                                = '07';

    public const SHIP_INDICATORS = [
        self::SHIP_INDICATOR_CARDHOLDER_BILLING_ADDRESS,
        self::SHIP_INDICATOR_ANOTHER_VERIFIED_ADDRESS,
        self::SHIP_INDICATOR_DIFFERENT_CARDHOLDER_BILLING_ADDRESS,
        self::SHIP_INDICATOR_SHIP_TO_STORE,
        self::SHIP_INDICATOR_DIGITAL_GOODS,
        self::SHIP_INDICATOR_TRAVEL_EVENT,
        self::SHIP_INDICATOR_OTHER,
    ];

    public const DELIVERY_TIME_FRAME_ELECTRONIC         = '01';
    public const DELIVERY_TIME_SAME_DAY_SHIPPING        = '02';
    public const DELIVERY_TIME_OVERNIGHT_SHIPPING       = '03';
    public const DELIVERY_TIME_TOW_DAY_OR_MODE_SHIPPING = '04';

    public const DELIVERY_TIMES = [
        self::DELIVERY_TIME_FRAME_ELECTRONIC,
        self::DELIVERY_TIME_SAME_DAY_SHIPPING,
        self::DELIVERY_TIME_OVERNIGHT_SHIPPING,
        self::DELIVERY_TIME_TOW_DAY_OR_MODE_SHIPPING,
    ];


    public const REORDER_ITEMS_INDICATOR_FIRST_TIME = '01';
    public const REORDER_ITEMS_INDICATOR_REORDERERD = '02';

    public const REORDER_ITEMS_INDICATORS = [
        self::REORDER_ITEMS_INDICATOR_FIRST_TIME,
        self::REORDER_ITEMS_INDICATOR_REORDERERD,
    ];

    public const PREORDER_PURCHASE_INDICATOR_MERCHANDISE = '01';
    public const PREORDER_PURCHASE_INDICATOR_FUTURE = '02';

    public const PREORDER_PURCHASE_INDICATORS = [
        self::PREORDER_PURCHASE_INDICATOR_MERCHANDISE,
        self::PREORDER_PURCHASE_INDICATOR_FUTURE,
    ];

    public const TRANS_TYPE_GOODS_SERVICE_PURCHASE = '01';
    public const TRANS_TYPE_GOODS_CHECK_ACCEPTANCE = '03';
    public const TRANS_TYPE_ACCOUNT_FUNDING        = '10';
    public const TRANS_TYPE_QUASI_CASH_TRANSACTION = '11';
    public const PREPAID_ACTIVATION_AND_LOAN       = '28';

    public const TRANS_TYPES = [
        self::TRANS_TYPE_GOODS_SERVICE_PURCHASE,
        self::TRANS_TYPE_GOODS_CHECK_ACCEPTANCE,
        self::TRANS_TYPE_ACCOUNT_FUNDING,
        self::TRANS_TYPE_QUASI_CASH_TRANSACTION,
        self::PREPAID_ACTIVATION_AND_LOAN,
    ];

    public const EXEMPTION_INDICATOR_LOW_VALUE_TRANSACTION                    = '01';
    public const EXEMPTION_INDICATOR_LOW_RISK_TRANSACTION                     = '02';
    public const EXEMPTION_INDICATOR_WHITELISTED_TRANSACTION                  = '03';
    public const EXEMPTION_INDICATOR_SECURE_CORPORATE_PAYMENT                 = '04';
    public const EXEMPTION_INDICATOR_RECURRING_MERCHANT_INITIATED_TRANSACTION = '05';
    public const EXEMPTION_INDICATOR_MAIL_OR_TELEPHONE_ORDER                  = '06';
    public const EXEMPTION_INDICATOR_ANONYMOUS_PAYMENT_CARD                   = '07';

    public const EXEMPTION_INDICATORS = [
        self::EXEMPTION_INDICATOR_LOW_VALUE_TRANSACTION,
        self::EXEMPTION_INDICATOR_LOW_RISK_TRANSACTION,
        self::EXEMPTION_INDICATOR_WHITELISTED_TRANSACTION,
        self::EXEMPTION_INDICATOR_SECURE_CORPORATE_PAYMENT,
        self::EXEMPTION_INDICATOR_RECURRING_MERCHANT_INITIATED_TRANSACTION,
        self::EXEMPTION_INDICATOR_MAIL_OR_TELEPHONE_ORDER,
        self::EXEMPTION_INDICATOR_ANONYMOUS_PAYMENT_CARD,
    ];
}